persistence:
  defaultClass: true
longhornUI:
  replicas: 1
defaultSettings:
  storageMinimalAvailablePercentage: 5
  defaultReplicaCount: 1
  concurrentAutomaticEngineUpgradePerNodeLimit: 0
defaultBackupStore:
  backupTarget: s3://tinyrack-prod@hetzner/longhorn
  backupTargetCredentialSecret: tinyrack-s3-secret
