apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  chart:
    spec:
      chart: longhorn
      version: "1.10.1"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  interval: 5m
  timeout: 5m
  releaseName: longhorn
  values:
    persistence:
      defaultClass: true
    longhornUI:
      replicas: 1
    defaultSettings:
      storageMinimalAvailablePercentage: 5
    defaultBackupStore:
      backupTarget: s3://tinyrack-prod@hetzner/longhorn
      backupTargetCredentialSecret: tinyrack-s3-secret
#    ingress:
#      enabled: true
#      host: longhorn.internal.tinyrack.net
#      tls: true
#      tlsSecret: letsencrypt-cert
