apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets-system
spec:
  chart:
    spec:
      chart: external-secrets
      version: "0.19.2"
      sourceRef:
        kind: HelmRepository
        name: external-secrets-repository
        namespace: flux-system
  interval: 5m
  timeout: 5m
  releaseName: external-secrets
