apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backup-cleanup.configmap.yaml
  - backup-cleanup.clusterrole.yaml
  - backup-cleanup.global-context.yaml
  - cnpg-backup.deleting-policy.yaml
  - longhorn-backup.deleting-policy.yaml
  - longhorn-system-backup.deleting-policy.yaml
