apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik-system
spec:
  releaseName: authentik
  interval: 5m
  chart:
    spec:
      chart: authentik
      version: "2025.8.4"
      sourceRef:
        kind: HelmRepository
        name: authentik-repository
        namespace: flux-system
  values:
    authentik:
      secret_key: file:///authentik-secret/secret_key
      error_reporting:
        enabled: true
      postgresql:
        host: authentik-database-cluster-rw.authentik-system.svc.cluster.local
        name: authentik
        user: file:///postgres-creds/username
        password: file:///postgres-creds/password
      redis:
        host: authentik-redis-master.authentik-system.svc.cluster.local
        password: file:///redis-creds/redis-password
    server:
      ingress:
        ingressClassName: traefik
        enabled: true
        hosts:
          - auth.tinyrack.net
          - authentik.tinyrack.net
        tls:
          - secretName: letsencrypt-wildcard-cert-tinyrack.net
            hosts:
              - auth.tinyrack.net
              - authentik.tinyrack.net
      volumes: &volumes
        - name: authentik-secret
          secret:
            secretName: authentik-secret
        - name: postgres-creds
          secret:
            secretName: authentik-database-user-secret
        - name: redis-creds
          secret:
            secretName: authentik-redis-secret
      volumeMounts: &volumeMounts
        - name: authentik-secret
          mountPath: /authentik-secret
          readOnly: true
        - name: postgres-creds
          mountPath: /postgres-creds
          readOnly: true
        - name: redis-creds
          mountPath: /redis-creds
          readOnly: true
    worker:
      volumes: *volumes
      volumeMounts: *volumeMounts
