apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik-system
spec:
  releaseName: authentik
  interval: 5m
  chart:
    spec:
      chart: authentik
      version: "2025.6.4"
      sourceRef:
        kind: HelmRepository
        name: authentik-repository
        namespace: flux-system
  values:
    authentik:
      secret_key: "PleaseGenerateASecureKey"
      error_reporting:
        enabled: true
      postgresql:
        host: host
        name: dbname
        user: file:///postgres-creds/username
        password: file:///postgres-creds/password
      redis:
        host: host
        password: password
    server:
      ingress:
        ingressClassName: traefik
        enabled: true
        hosts:
          - authentik.tinyrack.net
      volumes:
        - name: postgres-creds
          secret:
            secretName: authentik-postgres-credentials
      volumeMounts:
        - name: postgres-creds
          mountPath: /postgres-creds
          readOnly: true
