apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - longhorn.yaml
  - traefik.yaml
  - metallb.yaml
  - sealed-secrets.yaml
  - tailscale.yaml
  - reflector.yaml
  - jetstack.yaml
