apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium.yaml
  - external-secrets.yaml
  - mariadb-operator.yaml
  - longhorn.yaml
  - traefik.yaml
  - sealed-secrets.yaml
  - tailscale.yaml
  - reflector.yaml
  - jetstack.yaml
  - kyverno.yaml
  - ot-container-kit.yaml
  - grafana.yaml
  - prometheus-community.yaml
