apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - headlamp.yaml
  - external-secrets.yaml
  - bitwarden-external-secrets.yaml
  - mariadb-operator.yaml
  - longhorn.yaml
  - prometheus.yaml
  - traefik.yaml
  - metallb.yaml
  - sealed-secrets.yaml
  - tailscale.yaml
  - reflector.yaml
  - jetstack.yaml
