apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: mariadb-operator-repository
  namespace: flux-system
spec:
  interval: 15m
  url: https://helm.mariadb.com/mariadb-operator