apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-repository
  namespace: flux-system
spec:
  interval: 15m
  url: https://prometheus-community.github.io/helm-charts