apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ghost-release
  namespace: ghost-system
spec:
  chartRef:
    kind: OCIRepository
    name: ghost-repository
    namespace: flux-system
  interval: 5m
  timeout: 5m
  releaseName: ghost
  values:
    ghostUsername: tinyrack
    existingSecret: "ghost-initial-admin-secret"
    ghostEmail: admin@tinyrack.net
    ghostBlogTitle: 타이니랙
    ghostHost: "tinyrack.net"
    ghostEnableHttps: true
    smtpHost: mail.winetree94.com
    smtpPort: 587
    smtpUser: "noreply@tinyrack.net"
    smtpProtocol: tls
    smtpExistingSecret: "ghost-smtp-secret"
    allowEmptyPassword: false
    ghostSkipInstall: true
    service:
      type: ClusterIP
    persistence:
      enabled: true
      size: 20Gi
      storageClass: "longhorn-rwx"
      accessModes:
        - ReadWriteMany
      existingClaim: "ghost-storage"
    mysql:
      enabled: true
      auth:
        database: ghost
        username: ghost
        existingSecret: "ghost-database-secret"
      primary:
        persistence:
          enabled: true
          storageClass: "local-path"
          size: 4Gi