apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-storage
  namespace: ghost-system
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-rwx
  resources:
    requests:
      storage: 10Gi
  volumeName: ghost-storage
