apiVersion: batch/v1
kind: CronJob
metadata:
  name: ghost-database-backup
  namespace: ghost-system
spec:
  schedule: "0 3 * * *"  # 매일 새벽 3시
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mysql-backup
              image: docker.io/ubuntu:24.04
              securityContext:
                runAsUser: 0
              env:
                - name: MYSQL_HOST
                  value: ghost-mysql.ghost-system.svc.cluster.local
                - name: MYSQL_USER
                  value: root
                - name: MYSQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ghost-database-secret
                      key: mysql-root-password
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: tinyrack-s3-secret
                      key: AWS_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: tinyrack-s3-secret
                      key: AWS_SECRET_ACCESS_KEY
                - name: AWS_ENDPOINTS
                  valueFrom:
                    secretKeyRef:
                      name: tinyrack-s3-secret
                      key: AWS_ENDPOINTS
              command:
                - sh
                - -c
                - |
                  set -e
                  apt update && apt install -y mysql-client gzip curl
                  export TIMESTAMP=$(date +%F-%H%M)

                  echo "Minio CLI Installation"
                  curl https://dl.min.io/client/mc/release/linux-amd64/mc --create-dirs -o /usr/bin/mc
                  chmod +x /usr/bin/mc

                  echo "Configuring Minio CLI"
                  mc alias set storage https://$AWS_ENDPOINTS $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY

                  echo "Starting MySQL Backup"
                  SQL_FILE="/tmp/mysql-backup-$TIMESTAMP.sql"
                  mysqldump -h $MYSQL_HOST -u $MYSQL_USER -p"$MYSQL_PASSWORD" ghost > $SQL_FILE
                  echo "MySQL Backup completed: $SQL_FILE"

                  echo "Compressing MySQL Backup"
                  BACKUP_FILE="/tmp/mysql-backup-$TIMESTAMP.sql.gz"
                  gzip -c $SQL_FILE > $BACKUP_FILE
                  echo "MySQL Backup compressed: $BACKUP_FILE"

                  echo "Uploading MySQL Backup to Minio"
                  mc cp $BACKUP_FILE storage/tinyrack-prod/apps/ghost/database/mysql-backup-$TIMESTAMP.sql.gz
                  echo "MySQL Backup uploaded to Minio: storage/tinyrack-prod/apps/ghost/database/mysql-backup-$TIMESTAMP.sql.gz"
                  echo "Backup completed successfully"
          restartPolicy: OnFailure