apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ghost.namespace.yaml
  - ghost.database.secret.yaml
  - ghost.smtp.secret.yaml
  - ghost.initial-admin.secret.yaml
  - ghost.deployment.yaml
  - ghost.service.yaml
  - ghost.database.yaml
  - activity-pub.service.yaml
  - caddy.config-map.yaml
  - caddy.deployment.yaml
  - caddy.service.yaml
  - ghost.ingress-route.yaml
  # - ghost.ingress.yaml
