apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: discourse-deployment
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./apps/overlays/production/discourse/deployment
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 3m0s
  wait: true
  dependsOn:
    - name: load-repositories
