---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: load-repositories
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./apps/base/repositories
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m0s
  wait: true
