{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "tinyrack-s3-secret",
    "namespace": "kube-system",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "tinyrack-s3-secret",
        "namespace": "kube-system",
        "creationTimestamp": null,
        "annotations": {
          "reflector.v1.k8s.emberstack.com/reflection-allowed": "true",
          "reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces": "",
          "reflector.v1.k8s.emberstack.com/reflection-auto-enabled": "true"
        }
      }
    },
    "encryptedData": {
      "ACCESS_KEY": "AgBYei+OHT4P+Po+FZXZC0riLWgsINOYbwbKoaV7b7xTDFDU8kfPX9nPqE9zh2ek/0zx92e7LSr8WW3PlneHYle2sEf3DT2n4NItLz5GFXgsA/EKAHnEmcs1pSWDuxJNu5Xklwp4UvjWIpTmAzkjyigO+SSHj/R0rs2sbDn7wqS69f3kRcn6gFkPxMN32Jq+4AIJz1gFVvGToknVojPg5kGdxtqjhtBdNk6RNjCDkgqNRJrTGV3Ry4UQgESgW6GfwMZh8DQ8lxQi5lW7yqXB6dpV5jHhT3kr0kn2LX+UdhTsn/AT4FnKpHJLom34nuuiFYgAW20PVYcm1qxhc3R6AHTXA5v1RMj04hsZCkwT42ATyCh4q1DNYIz0u6Rw6Y8s39sz+Gj+3w5OdRVMmU5bTLKmk5pdPtvSHJX1Z4Bs4mTeRhDFh9ck87bqunSPm3qh6Ky5myO5ll3/cGTXu9JcrbyYQoyzvKJCdbyxY6Dcy38L/j+onCNZ6Sy2vqc/HFkGjkkAfgXP1jBtT/oUy7D1fUtgN8Vy/uCFS5PiQ0BAelC5tBe1lEOLm5OQVowT5dtZbRZ9oXLwhwfY//lf8O8FmGZwFeTv4cmiz1OIlsWX9iayrNOzG71aHuE8SYYE1AyVrFntXfI1CkCBL1YLwemlAv330IhkNcpVaNR9dGs6qpozdTRwn3/WTJP/cwx9LVXLIu6O6y0ezO3xeoRP9tC2taNdHN/pBw==",
      "SECRET_KEY": "AgCL+H5aqRITKlnyOsI9Br1WqzbjHqS2WpPsvYowOLZnqDHUUATwDAs+deblq/faXMa83d40HrKChf7upp+ktSLGTBC6ub1gcdHz1XklGJ4znBmq41BzR1o05Ytwa8ksDv6VCZuEG34StvNVnZ7EJyp2rjWoA8KlYQvkJDksRCkMXl94fJvGpF0tvb21Fkr7wpp0Kt6j/mWzf10VrtjAyGVaagfunte1lsQjZywVUFdr7RL6Lsyf5KGIHH7nc04En5l1tuhKfcLHWTn0FGAAO6snqKjxMzQyqOZywo+U+X7FofSTaWTwzjpD6FcRiMbNie1qSFsvGtS86hM4d+Kwzrz5gHNtSZR5mGGEI+LUJ/tKpgNH8KLbXjBU7lv1zyuTEs48HrJUm1F11D01PHL5dLlBzjid/bn+yaldh0u3x+5CGcruWahQKCWU2KqOYQqaNAyB58MyWx9vOy1Do3ddX+PqQUUk5Vr0yhXkIWbFk5fg1aav43oXe0YaZoeqq9Jvya3LG7CDxsPe1e0wOuNxQGn+ga+u2fUxEkzKc/xuP0G+8kkHvmVeaeoz22fELXTVsAsXu6ibWFJMpOCXcFCzqz9/gKvZXQv/pR3DDkuSdPwDoRWrqnzu4tR9tdoLWs5O5e78BWPeHtTr2v40VvmutVvGbvP/US9muwSGn4guVZAyBWRsHQNU7PXKhPDCKsizpoEhLc2z6C/652V9PtBA9aFlUuloparWN3kI7Dq6ajFqMYLeE6MTRrRt"
    }
  }
}
