{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "tinyrack-s3-secret",
    "namespace": "kube-system",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "tinyrack-s3-secret",
        "namespace": "kube-system",
        "creationTimestamp": null,
        "annotations": {
          "reflector.v1.k8s.emberstack.com/reflection-allowed": "true",
          "reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces": "",
          "reflector.v1.k8s.emberstack.com/reflection-auto-enabled": "true"
        }
      }
    },
    "encryptedData": {
      "AWS_ACCESS_KEY_ID": "AgCPKF9/HEU1MWc8kE5Bq4fHKU1lpbmM5V9SLVB1lkzPVfUo/lW9Ff9xWJsMNrwwIuTg68zQpXFBV2CCfF/X/NtkTIpvRILvbZipBkjTHa9+Mzz+BJGtzpL3kc2tHcwdsmRhMkI6snZT89NsRKv1zCLZEjPArtt3z4kTCBh2WQKL2NL2PFEwbC9E6467hGTpyrnBE14OYdrH9Ynt+UAc7WFmhaA6tbIoIK2KoT2z4LFCpAFqwKuwQ6AzAbgF+hsE1uk3syENfR1Cn9hmYkx68/fibvQC4evnGFpd9KvginrUtSQG6cao6HD9lHz7NNAUAud/V/Dio5BKVKjUlY5vuMK4+Eb+5c+t/FC0ibNtlIwo0qVHPAgt2U4+UtsXoigwxgAYbBOF0GGUS9HYEptj4JdhxjszXVdd1C2Z462HFHtdElwBrQcpK4wbdzss8sdVlOgd5oAXgIgO7p9mbsAkCSpH+0Pab9Zh+RdLleXj8f5cEaS3mJTcdB4iayQK+89fmmNjp9V8rGEkw8IV39wT3MOZy6PPbIcUIBqkRNWCyL9kieXNxTXxQATSljQROWnzfAnTyqthQjoBfR6kSmQdHA+tDsPG750MVQXM8Yw31Dv9go9GTPAV8QiOUy9BXo8sil+JM7s2EDr1sxgnLiu5JyXjqHB2pEe6ep/vs8lNkQGvYRY8Jez4qspQNQcepcYJ9SDCkPlFMh9yN5KvawkrlFC7ebCLnA==",
      "AWS_ENDPOINTS": "AgAISwAr5uAK6r/fBvaK6UhCet9K9jH7oQw/EaXWq53sL54R4TvVC0kp142pOkz5J1IAED245gjW2VkDf/N4Vv8Sbx30XjS7KEKEfQ07CJYFLFxkKTT8RDdcRdMptZyCsyNJ8o+ifs9+m8mpxvlZP5uBjYogrWcCSb5xN5K4lSzvrRMOi4wrLcwfGiE4zzuxRAxc0akO9snAVhIHZz/aYe9Zk7WsKHew4iHtKV7Yd9ACL+Pb/olmS6IYdc2OKWRVyqo6qPoinZNeQ9jqali1zk/FZ3GdiuytQDBiiLnss/3ybFj5Sjv9FXJNcJeYGhwveQBMCeUpg2PTUHNCPjsLhVrlyCGZJDeg0DHgJQco/anF05TEy8to/FAXgrFA1Jeiph0KcEEdWr6oOT5IVRWiBHDmXhi7r/LOxmF2pXqRqMfKaywH535z26iOgPJle+apb94ha5TH5R4kf5/zajZ/6HAbZ0nFeqPSZcsp2OW9eqrT5aeuKIjxgV2ZJXYUu1pAWUuunweYJYWpUHphjni/xRZ41dWws7pGgNFV0OqMh6P23Yv8lNYhcmqxDRcTEHhmyodmd1D3JPDkEr+92aDvdlY70F6i1D/7pQ5kb4tM4v6Ys/BGX3b2qVvh4lukHr+wo2l/MHHLdncAD5VU4GAPVWefp4R5KEHCpOmuewHx/DV7BgUxpudRGSR+BGZhZWTzkGNOqyFgOng70/HpY/162yI093melVsUAzklQYo=",
      "AWS_SECRET_ACCESS_KEY": "AgBpFCdCV841dqg7V9hDV6+ZfdKuloq48fWhebzzaCIYKKjT0mUnM0gX8zmG0fVWdct+HfpfHZ+DiQLKrkl5TM6zauqN0H2+R0dovNV4eyOWFflc7yyRZ8bacmc8ai8Id/XtXDqSiZ7O0/A7pwNwG0g0Y3JfSFou9m4TLoaSrEtlUbCYquy/8j+gGiD3gd2TNjAnpopestmAfO1FP9jyuUn6iMoGIMWNA3sWIeXQePM/9fJS8KqR9MJ66zAyXzdA5XqGYKIw52SCiAi3RriSNt4pYue0SitesDvLEwyWjAXRJxVOEM9mXRYjdv0cr2BPJeE8L6HbvYLBAimscEQ9hb8dugcFQ+fZg5O4pYU/POBiklzvmeWD+VrfB/+PTf4DoGibLXk0gqoxAqaDNIKELq2g2oFkuGtcCoj5rabSfad0RxMnAbAFjIesYJlE0+JG1tS2gFZrAK7D+UBUDyP7atTcObNvwBa79PghSRcISgjtl63KAlEr9F+S9c7vM0xRISNcm7rP2JM6dol1pK6CFD+Y58Fp3o9+yDDkYxCxce9D7KlaZSdj3EBka6+bOSw5ASf3XSCXW85mk658voftq6Mu0sxYWaMXC0b3IDFdXpTECgDEoHnW1E5rcRzNywmqfyDMz08FiekJxt4l0QIsA9nRyN9W0YbR2SgJe/lTees/0PaZPgLTu3q4jeLekAUS8U+AEHQ+ZS5ZSBWOHDqyDWCdbvPXSF0jRjMVxEQf6CheRfLbsp1Cadpx"
    }
  }
}
