{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "tinyrack-s3-secret",
    "namespace": "kube-system",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "tinyrack-s3-secret",
        "namespace": "kube-system",
        "creationTimestamp": null,
        "annotations": {
          "reflector.v1.k8s.emberstack.com/reflection-allowed": "true",
          "reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces": "",
          "reflector.v1.k8s.emberstack.com/reflection-auto-enabled": "true"
        }
      }
    },
    "encryptedData": {
      "AWS_ACCESS_KEY_ID": "AgBOM839BztyoDU9ozgPGSu52FJsez+w1NSzPQ/H0lYPrsly7f9fuOrIEy9QKG+ZZVQlLjtxkyCpcE4WZeMkR05DL4sANC7+J39Eyv+tvq5Zii3LPugSQl9e/bV6aszdYH01g/Ew7eP5p8RnPCc8MaYAPH8nLCWTP8T0Am8pBa4CofuqW5tJOdklxVZlvVzwVWil/4k3GfjuLZ9wR6Yux3MAm5QWk/cj/T1gM9BE/AzHwTagUw8q73yc86aWMzCjkGgI3KpSEiydBNINgaIiloYK4x9ypLWQojbtuaijBphwWXb4x73q1N1l8TR+RWJxudK4WGMwiKU6ftUvTOw6Fz7qLQJeQymGqIHBT68liW/E+fpTAPjqBsyA+bS7EnHDDCDYatSFBMeI69tXzpkCxsCMQabG+B9dCdXjdoHHAHcDFIqcQU46uu8vJweJrGjBf7MKK1+tjHaCUtuxpmLaYyzKtZaMYOSS42AlMPW8QiZKPlq6B5+F5aVgF9Msi9VqL3/L0yWFXHKy79GAIlLT/Y2iFRLmmAcS2JZNvPoyfDdedzpzNCKLT0McQ5AFjIKKtDPAlhtz+O6D+hz9YzRvLeWMoNbXCyUwkuyFer4vU35awtQJ48Ufdj0zsQo03TticjKRgjiAKKI11gv5G2VFUamTG0vQzJ1nvytVQZRWHhT6KTByXLvTn/2L9yGP8nAUlbW+87YjsZU7VQ05muRsYP1XVtg4wA==",
      "AWS_ENDPOINTS": "AgCEH4HEK0noSjQRaDb+8QV0n7nSVV4dN8bTDqB7Cm3BqTwZDpAA+vNOUjfxipGgWdu3uhcLS+MnSL2e8Zlkp0qj7pe/2e2/bUQ5kA592ZbnNj1D7X6QdF23FSF2FN7AH35YIxQgnZt4GKg1pFAphDufc/i9PrDCWZDE5V+MZTlZZRJmrPEc1aEUF03jZF32zs75VJ2YY5Yx1H+W5SN+cae+RV5EgN0NmyWrZwujLEpVHdQkQHW3dr6lzziaRGRjzxp03tFqWanpnrfdgeafhQCc3WKgq18ecCofe+VcHZOaY55eoaOX8Npj/mWBUY8n3avqO1ItFgTlE06V251gDuLFVCaP14WASW6X5fOTwPAmLVq30aJVSdcybFS3Wt8ZwWua7r40rRSGdjlpe+eef52vJjXH4dKOWA/gy9h75JmKoDf6HaFZy9dyD6zMBfP0TSU4O/CBDjszpm4KzkfYZVVOQib3Tc61d1cFhYSJH/mJd7pOG27Mxp4qnHwWGmEb+7EtXHPTQavctdQXhLspbDH+CPOckkekmAx5+B9wOHR74/k3A/eXo9IPHxpUw24yM4OtkiUuuIJgFDUCEF/IdRwha+Jtq4pF5J0sSHfgv3DjX3nMq/ezuGlgry0j8ARgpid/VVo8ul/u4vyRiaxrDZDTRbimIXEvVcob681m9i1wAJldnEFUXjbwkVoT1q1rxu3/GppxlXfhU80I53t4St2s6/IB9pYF",
      "AWS_SECRET_ACCESS_KEY": "AgAZ+rIC7+UijSLnnqwKu/KFHXnkLbwaCPE/+AH0T+w/WuOWa3rAZThcWHz+H4BAXyDTEwevN7VijZzdaUj1ULwnaFrufndamIsgfJ5hmjjXifEmwB0XkAXX4Z3SZqq6anhu4D3jNe2oQHqAheFTQwJpafZBHqOlgeoxSWzhnbbfhp7luIdBUQL4rG8rADmhJYIjCu6qotv9ma7WSP4urm0uifiO1yHpxf8/Fe92gMBb9ejG2K3iVwSi/ho4r8N+Mf0B7YhANrTdJJCHd59J4EN7OjGgc3IGO2Srmhfin1stWeqR9P48Hcv/VT8f+iLXbFCBNHcj6I5Pq/mTUDX7IXpguCSk+mfrCT1tctxGXz82tTcULhEhgu5gYWFRJfn3FwBxdY17qbydCV2Re05RoFz8b69ykcCjaqBZUoI/1h77/RVDZwo6mka7hAiLOAOB/aK6v2PgEADrKjPGAqP04lxDKRTvJ6c9/UrBtQjEWR3VqTERHuHTRiN5QVYMJptBRcUYlzPiC9SAsBNwO9VYtIwHRPGT+C2Xpako696w8mQAPFQt6nYk1z6pvgcNoiEE5YthUht+x+61CeutPAH9ELbdgQ6j+K2goNKy4dpX7DbOG4GQAKbY35bOzVDv/DbdXI2EaJ54U27/A/QFhm7ruTlxMiCPWZDZsKL/wID8sy6dlnT7G0Ez1Wx7mNYoLujZoxKxl6bskH/WJcdZk/SID3kpxtWq/47GFjY08QIVb3jBKdiUr4e4KSUf"
    }
  }
}
