{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "cloudflared-secret",
    "namespace": "cloudflared-system"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "cloudflared-secret",
        "namespace": "cloudflared-system"
      }
    },
    "encryptedData": {
      "CLOUDFLARED_TOKEN": "AgAHcjSES8FYo8xb5elj/LCVbqKYSKKyCYc396rXmZ4SX4/rwjicPJgqBW6YhqObRX26PbLtRtYVwFR36bBh3dAQVAK85mxpsai2Z9o8v74EFiAOj1bncQWyU3E9zHCY8vbRIk2JZCokhHvtNrKd15a1NkhtHNccftjxtRIYDwjmnmC5aBgB7TqV6l1nPeWGkG5bIcww9mwQuJYqKHloNqNFPriXCRuNOpF55O1/g6TSQ09UooDmfPzefQ1swJ4sl4A/b+7dQLwWF03U3Za/X9c4SvTrTKDU9rTzQt8rsa6/93TbIu+qOpoc/c7Va+KTq2xookdtg8XPpspIYsniNyHJ9V+k+gSr4EBQK0nqFhUvrS6CI2wK8Ek2urWfu/h9tSOA9ypMry2e1p5mAgVUeS+o2dzWqreFKLhb8px2/NCvLflrZmqfr67tLzmHSnLYYlm7kD9EaTysyFh5hmJqL85B4A1N3TKMXr3yf3kIyOESQsLZJ51wPmbTl202g8usnWFP2FRv9HL7X09UZ+YhEIxBKjpXOoCMsuCFxt2JEW3gFTV6C4rATgmElGs6W7Uww5iuD4+3MUrKc/rabDt/FMYJ3MQFxE/4k4zmc1ovvu5IWrmsXSe6pyL3CwKUn8In+FuKcBMoo+4kKu2qk05HmBDsNptQHr11eCbRlkZs/k9HiKtyMvS5hQurvK1tCwPuqH7JywEGYqde+emQro3IIKZ9xvmDMGboRQxAwlEmR8D3qYLrZCyQsWhhu3N7IL0z6DkZmf7voFgJdeozcI25BJiGfDSu69X00Hqgtylu8RaLFRdlso+JcGj/HRFdE1KNzAhQhHg4rkamtFHCiUOUBBhsyYlmUVEWzB5JyFXQf/6AEWS8310n0ytgIlOOPTh7szvYwhEstda5T6QTE/X4ip6J4Xo6yvi+DBv58DJdkPbL5/AZWreMDzIq"
    }
  }
}
