{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "cloudflared-secret",
    "namespace": "docmost-system"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "cloudflared-secret",
        "namespace": "docmost-system"
      }
    },
    "encryptedData": {
      "CLOUDFLARED_TOKEN": "AgAx+pCXkILdi6uAjNmCIVjHt6kFuUwKrc6oeFAhbcmod6TQHY5NrEDk7QGSCuyNHbArJ8y0eb6qz1TloVajK7RkPfKNhzGhRfYbvzqT+M2G47Gtgn1PBVv8y+2aav0OviFwFUzra87wvxLoaPLyzrA/h6XWkNamzUVRU/kvQjHx9WuqyBCmvdshIjM8SVglvZJYff+9WD99MNyN1F+tDgQW8vBklE5gqugz4AaPasJsbtzr9rxlwLNLhj8GDXXg6pkVfXzk1PAMqR1rSvFCnnUSeW3PuLagtXMmMj7WRJZZxWnabYChPKlQ1utj8icsA4gQJyiC1xam68WiSLuBoEWEhRPBdnBd3gJqx6EkLLfC52svirccH1FLxiTUGwmGeOerfll8DdCwzFNKkIee9MT5uDDComI4hI2lsvWxiIEqSJgW4X5cechycPlZm0FFMJeV2TwV80I2VRnijlu2qlkCyIN+64un69+7VEZbbg/fTLRXfaDVU/cAawjlADgrWcpLh6S+WLln3WO8+U6J0gi4uoxmP8izSI+hIXflyQEfoRC1nYZ8WOyL/E5zG8e1z2NG2MmCLjytvtyWsSpzsTdD6sUllOWXoFw3pIVhekJ9urDzu5bwyW9ocCTAuf/bVIVczSQjhKxTXUDhzrmDI0pEEgpPR+VcroJGZ0JszmgSd0OhO0sORunF1lfjKDKvyWlTVjboO90O7eo4IiaX7ZacTKN49I/H5j0WXNhqh11Paau3Y2udEFpI"
    }
  }
}
