apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-release
  namespace: cert-manager-system
spec:
  chart:
    spec:
      chart: cert-manager
      version: '1.18.2'
      sourceRef:
        kind: HelmRepository
        name: jetstack-repository
        namespace: flux-system
  interval: 5m
  timeout: 5m
  releaseName: cert-manager
  values:
    crds:
      enabled: true
    enableCertificateOwnerRef: true
    dns01RecursiveNameserversOnly: true
    dns01RecursiveNameservers: "8.8.8.8:53,1.1.1.1:53"
