apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - tinyauth.namespace.yaml
  - tinyauth.database.superuser.secret.yaml
  - tinyauth.database.user.secret.yaml
  - tinyauth.secrets.yaml
  - tinyauth.database.yaml
  - tinyauth.config-map.yaml
  - tinyauth.deployment.yaml
  - tinyauth.service.yaml
  - tinyauth.ingress.yaml
