apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflared-deployment
  namespace: flux-system
spec:
  interval: 15m
  path: ./infrastructure/base/cloudflared
  prune: true
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: sealed-secrets
