apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: coredns-configs
  namespace: flux-system
spec:
  interval: 15m
  path: ./infrastructure/base/coredns
  prune: true
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
