# longhorn 기본 로딩
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-configs
  namespace: flux-system
spec:
  interval: 15m
  path: ./infrastructure/overlays/production/longhorn/configs
  prune: true
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: sealed-secrets-production
---
# longhorn 배포
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-deployment
  namespace: flux-system
spec:
  interval: 15m
  path: ./infrastructure/overlays/production/longhorn/deployment
  prune: true
  timeout: 10m
  dependsOn:
    - name: longhorn-configs
    - name: infrastructure-repositories
  sourceRef:
    kind: GitRepository
    name: flux-system
---
# longhorn crd 설정
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-custom-resource-definitions
  namespace: flux-system
spec:
  interval: 15m
  path: ./infrastructure/overlays/production/longhorn/crds
  prune: true
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: longhorn-deployment
---