apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-deployment
  namespace: flux-system
spec:
  interval: 15m
  path: ./infrastructure/base/metallb
  prune: true
  timeout: 2m
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infrastructure-repositories
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-custom-resource-definitions
  namespace: flux-system
spec:
  interval: 15m
  path: ./infrastructure/overlays/production/metallb/crds
  prune: true
  timeout: 2m
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infrastructure-repositories
    - name: metallb-deployment