apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ot-redis-operator-deployment
  namespace: flux-system
spec:
  interval: 15m
  path: ./infrastructure/base/ot-redis-operator
  prune: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infrastructure-repositories

