apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-production
  namespace: flux-system
spec:
  interval: 15m
  path: ./infrastructure/base/prometheus
  prune: true
  timeout: 2m
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cert-manager-cluster-custom-resources-production
    - name: reflector
    - name: longhorn-custom-resource-definitions