{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "tailscale-oauth-secret",
    "namespace": "tailscale"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "tailscale-oauth-secret",
        "namespace": "tailscale"
      }
    },
    "encryptedData": {
      "CLIENT_ID": "AgA06sQc/fqbpH6aRqzZnhhsf1BFKu4GO7QAUcx96IfdNGemjCWj+JQjxW4prU5BoM0nvGWueO85o/BXDqrKixnzYv6gNSHHflAodoB8kXMcQJP1C5KxY4db51R5L8ezVOHN0KRsOrHT6pY00eRRNKDZPz3V79p4qUwrfOZAAcM8esEy3jsSOjlr9tlfa6D76tuH7L/YRv8BxPLm4bJi8zNVQ/BmexVhY85G2IW27q1jf3CNZyHxm4S2x4BQWORfhbvx8mzndxrlufOHSX9CU3LoAfImEccvXsoDB7YYWX1Osg0CE0WH995nZjoadbdoKTfa/D5hXNLHfilveIge2aO81n2/ErMZ67idIxwhB8eq1DUs0y0+BjiSKs6Msg2tIl9txXJEl4dpE5RwCvGZI7whDsRdMIivEsjF/8Qg0o9RMBmkP965pduwcNsATiAOj7+LTVvI/DSqiGQ1fJmgvRlDS/hxqlvFoYK/6J4lchC8w20gV9ZaDLQnkDQYB8N0+WM30bZhbbXHVIJKHWOU1RXgCLL99ReQK53q5OIQN5zLxxT3zFBXra9nV/xfUUJGztXZT4FBGaTvEv1P5QkvVGP7RlLzSghF2XSNuDhuvYQszf81rOUKuTtXJwW9uabOvU1IQuSnXOL/6eqIhN2brtOpjouxcncluaePY7RRJRex9YA0moqygZ6hP6mGpo6LcX5JsMQ6WcETkGN6eBhL/0k3SQ==",
      "CLIENT_SECRET": "AgBnPhTWUY92RnDVFO/kUh8aSTUGFCOHp3vn/SCsi1pJVitrCoX3SLi9So2wqohfgHkMjis5qmf/JUEP0Py+XwA5YslEoVRpFMcbGFLxXefQc1km5zFZIkivXoKnledMyahy8bfF7u3dDLJSM0sXXUrTU0LlLthvQbUkuZZyHzBBbPMYZGfuZMNXMEsmJft10y1ypIU02OyqBUjDg3tnUVi1o42RQgQST26nncZosRHkm0sauuvkb5A9/42wemhXizwcfgSskt+KzbiDSkE0b9NWX28P/3VzppoCwBRtKVfAVPS02mydwZu2u2NpxAksUVaeuWwL+Zv8uRIyOqDA11VhUbxNGW5whcslEh9lXDaq7HUY2HKBZhiXN/ELTdXDMukW1COPha3ezOgPC7ugMGxI/mNP195lfhDrS4g5O/u7GD2+j1tFuns0NsGh0J2bzLtkTa9PTBDu6PMxMXjOfpfxDu7py4uGQedfZnG5Wvm2LUUkjkvHnDIO8sDrQ6mpDgAe2XVTdbLn//mGhZYOlq46o5J2lC4iaGu8TFRo5MshT3gy743FVb4n3pYFqHlQRozaCYahGSBwwBqbxhlx0fRldgCWwcR/0fOH1t6RHge1MjoFGdVMJAhAAJOkvRv5am27SUJdD1+FY94Ngagjn5lT2aT7JvYHXkOzyK6it8j07yb/ZbipLm8yga57TXOZylPKfLRJxwa8+XI55Hk0ZL15IzVRroJjkAPrHBvAvWz1kkfLeYJdpzGr1sxmtj1wV1UuDbhRArzLcE8jMNgP4rSN"
    }
  }
}
