---
all:
  children:
    k3s_servers:
      hosts:
        tinyrack-server:
          ansible_host: tinyrack-server
          ansible_user: winetree94
          ansible_become_password: "{{ vault_tinyrack_become_password }}"
