apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - issuary.namespace.yaml
  - issuary.database.superuser.secret.yaml
  - issuary.database.user.secret.yaml
  - issuary.secrets.yaml
  - issuary.database.yaml
  - issuary.deployment.yaml
  - issuary.service.yaml
  - issuary.ingress.yaml
  - issuary.cilium-network-policy.yaml
configMapGenerator:
  - name: issuary-config
    namespace: issuary-system
    files:
      - config.yaml=issuary.config.yaml
