apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - issuary.namespace.yaml
  - issuary.database.superuser.secret.yaml
  - issuary.database.user.secret.yaml
  - issuary.secrets.yaml
  - issuary.database.yaml
  - issuary.config-map.yaml
  - issuary.deployment.yaml
  - issuary.service.yaml
