apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: memos-database-helm-release
  namespace: memos-system
spec:
  chartRef:
    kind: OCIRepository
    name: postgres-repository
    namespace: flux-system
  interval: 5m
  timeout: 5m
  releaseName: memos-database
  values:
    image:
      registry: docker.io
      repository: bitnami/postgresql
      tag: 17.5.0-debian-12-r12
      pullPolicy: IfNotPresent
    auth:
      enablePostgresUser: true
      username: "memos"
      database: "memos"
      replicationUsername: memos
      existingSecret: "memos-database-secret"
      secretKeys:
        adminPasswordKey: postgres-password
        userPasswordKey: password
        replicationPasswordKey: replication-password
      usePasswordFiles: true
    architecture: standalone
    primary:
      name: primary
      service:
        type: ClusterIP
      persistence:
        enabled: true
        volumeName: "data"
        storageClass: "longhorn-strict-local"
        size: 3Gi
    readReplicas:
      name: read
      replicaCount: 0