apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: memos-storage
  namespace: memos-system
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-rwx
  resources:
    requests:
      storage: 2Gi