apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: memos-database-cluster
  namespace: memos-system
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: "enabled"
spec:
  instances: 1
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 3Gi
      storageClassName: longhorn-strict-local
      volumeMode: Filesystem
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: 30d
    barmanObjectStore: &barmanObjectStore
      destinationPath: s3://tinyrack/apps/memos/database
      endpointURL: https://storage.winetree94.com
      s3Credentials:
        accessKeyId:
          name: tinyrack-s3-secret
          key: ACCESS_KEY
        secretAccessKey:
          name: tinyrack-s3-secret
          key: SECRET_KEY
      serverName: memos-database
      data:
        compression: bzip2
      wal:
        compression: bzip2
        maxParallel: 8
  externalClusters:
    - name: memos-database
      barmanObjectStore: *barmanObjectStore

  # enableSuperuserAccess: true
  # superuserSecret:
  #   # username, password 필요
  #   name: memos-secret

  # 신규 클러스터 프로비저닝 시 주석 처리
  # bootstrap:
  #   recovery:
  #     source: memos-database

  # bootstrap:
  #   initdb:
  #     database: memos
  #     owner: memos
  #     secret:
  #       # username, password 필요
  #       name: memos-secret
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: memos-backup
  namespace: memos-system
spec:
  schedule: "0 */30 * * * *"
  backupOwnerReference: self
  cluster:
    name: memos-database