apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: discourse-repository
  namespace: flux-system
spec:
  interval: 30m0s
  url: oci://registry-1.docker.io/bitnamicharts/discourse
  ref:
   tag: "16.0.2"