apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: redis-repository
  namespace: flux-system
spec:
  interval: 30m0s
  url: oci://registry-1.docker.io/bitnamicharts/redis
  ref:
   tag: "21.2.5"