apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: longhorn-delete-snapshots
  namespace: longhorn-system
spec:
  task: snapshot-delete
  cron: '0 */2 * * *'
  retain: 10
  groups:
    - default