apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: longhorn-system-backup
  namespace: longhorn-system
spec:
  task: system-backup
  cron: '0 */2 * * *'
  retain: 10
  concurrency: 2
  parameters:
    volume-backup-policy: disabled
  groups:
    - default
