apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: longhorn-delete-snapshots
  namespace: longhorn-system
spec:
  task: snapshot-delete
  cron: '0 */1 * * *'
  retain: 1
  groups:
    - backup
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot-cleanup
  namespace: longhorn-system
spec:
  task: snapshot-cleanup
  cron: '0 */1 * * *'
  retain: 0
  groups:
    - backup
---
