apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: openmediavault.time-inconnu.ts.net
  name: openmediavault-proxy
  namespace: tailscale
spec:
  externalName: placeholder
  type: ExternalName