apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: tailscale-pod-cidrs
  namespace: tailscale
spec:
  hostname: tailscale-pod-cidrs
  subnetRouter:
    advertiseRoutes:
      - "10.55.0.0/16"
      - "10.56.0.0/16"