apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-operator-release
  namespace: mariadb-operator-system
spec:
  chart:
    spec:
      chart: mariadb-operator
      version: "25.10.2"
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator-repository
        namespace: flux-system
  interval: 5m
  timeout: 5m
  releaseName: mariadb-operator
  