apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-translate-storage
  namespace: ghost-translate-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: longhorn-rwx
  volumeName: ghost-translate-storage-pv