{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "cloudflare-api-token-secret",
    "namespace": "cert-manager-system"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "cloudflare-api-token-secret",
        "namespace": "cert-manager-system"
      }
    },
    "encryptedData": {
      "api_token": "AgBqyQslqb5lG3zcywROhWd/sZn3S7HeuTpW3KydKCcknE9xwQkkU4Q5wMc7IGcePjzwJnSs5VyPUgnkLp3UILpj8tZk6Dck1w2jhqkZR3wcOoKGBSDGUFnEzEIHGKh0rVst8iQePoM7ASotNY5yH/C3rD1tAaa+obQaLByMEKFK8jYaEmCRmufsWdns7KPLMg9vlIc/2wVKzul0tnjc7Z7Gb8d8mh+Xnv2WM1ZRDC1N5/fE4PKYJ9Oa2OhuL7FGOTeGAJvjSElS1NAh3y2H80IeEBip3S9bsp1B4PUeqC9bwMm6KAyXOgFZFJgg1qtTuIwkY9HCWJaGlRj/C+fl3WqIAeCVw4OosGghCyTjXgVkzA5v5xSK+5ENVKbqC3PvwQ0yG3/Mn1QnfFCB25miV3tGpbVRumbthX4LD0zQDAWFhWbMxRRrVGz14LRbG4tiDM5YZn902BHxQ8Bey5J/X3voAzfebzB7Gj3nFpzzN/HQ2faFfRFqcL5YilczBtjMcO0Pn8m9MdTL3/S3mtM8MgimyAWxVWAckIRc88z0uqeVghUB6Td3VJJ1GkP7q83pGgLfsK/IU45xiZsaMcF+h00kWiMWLBK7FEO7M1CT4S7M5WXN8myVH9vkC1GIKzrt+LcofmbS1w8+6uVXB6bvPHEtdumWY+ouAVyAQbiQSjgsEulDamJvrxXBJ+gq2CYbj+n8rH9mLVsVBdQP9k1lXhhF8YzNv6XZTwiN54NDW/Guwcr9F9uSAjVJ"
    }
  }
}
