apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale-install
  namespace: flux-system
spec:
  interval: 15m
  path: ./infrastructure/base/tailscale/install
  prune: true
  timeout: 2m
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
