apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp-release
  namespace: headlamp-system
spec:
  chart:
    spec:
      chart: headlamp
      version: "0.32.1"
      sourceRef:
        kind: HelmRepository
        name: headlamp-repository
        namespace: flux-system
  interval: 5m
  timeout: 5m
  releaseName: headlamp
  values:
    # serviceAccount:
    #   create: false
    #   name: headlamp-admin
    ingress:
      enabled: true
      hosts:
        - host: headlamp.internal.tinyrack.net
          paths:
            - path: /
              type: ImplementationSpecific
      tls: 
        - secretName: letsencrypt-wildcard-cert-tinyrack.net
          hosts:
            - headlamp.internal.tinyrack.net
    config:
      watchPlugins: tru
    pluginsManager:
      enabled: true
      plugins:
        - name: flux
          source: https://artifacthub.io/packages/headlamp/headlamp-plugins/headlamp_flux
          version: "0.4.0"
        - name: cert-manager.io
          source: https://artifacthub.io/packages/headlamp/headlamp-plugins/headlamp_cert-manager
          version: "0.1.0"

