---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-telegram
  namespace: kube-prometheus-stack-system
spec:
  encryptedData:
    bot_token: AgBg6Sjy2ei1+U7bu5NHvvxbt21M5i3tUcNJussGZ84tRm46lZErV94/v8QiaxulYskBetTeFBOrEFoJwNZAo9F5Uq+zwPitGEX/MMgsmfEtZcBWNMjPRcR3gXDi9TB4F5YrgWRLALiSbI5IH9BRnsI0RCvE+OM2osNnBq4UshV+8/KPJGOyINOivyknVLezRrhcBpBbDRR9Kby6qJxsSthXH9qQGx+PfTGyyO3/XlXpLbLHZwb7HEUNxj3r6o/vPIYmZQmR+SsUxY1/KnOA1J8C8UaMEMsRfALSmVlhnLSJkzU5X9PFWd6luyde2K+92qz00SAC7v9Urhfn9aRZ//WHmmKd493ngdf2VAzt18AAUq2TVCCDdnaXs+XiJjU9xI+NNA5zHeo8KHI5lLOS9rHpe1BO3i+JNIWuglFjbh1NPss4W/H9XA8ifD47cQhR+Fdx29ExCrGkv03/mwxncaHd30tttBgdanariIvNYNdHYBYzUD316NE2EVzJZMCsw/T5H3Kv/kj5EbHzQxg/EfC039XmOMTh9S4vYX3dZapelue2dur5YuZwy9VhMsNT7dR9xUOgGW89Vv3teGyeksrh2EBrWgJsV3i7rLEChHdGNyPUKNUuj0giVRHX6WqkZxHelML0QLxLesM12VJApyjISUkicT5LOZje3f1j3sV1jX5F3q+v4cjQQpcpQoD1vozrMeRBVmEVvpjCGAxblBkzsJGrnxeCZi2x45E2c13rYey4loretQrgF5cU/Foo
  template:
    metadata:
      name: alertmanager-telegram
      namespace: kube-prometheus-stack-system
