{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "ghcr-secret",
    "namespace": "kube-system"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "ghcr-secret",
        "namespace": "kube-system",
        "annotations": {
          "reflector.v1.k8s.emberstack.com/reflection-allowed": "true",
          "reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces": "discourse-system",
          "reflector.v1.k8s.emberstack.com/reflection-auto-enabled": "true"
        }
      },
      "type": "kubernetes.io/dockerconfigjson"
    },
    "encryptedData": {
      ".dockerconfigjson": "AgAEsUcbAfUccAXr+egx0ulqEETowgyxNDKQr3zpy8QSXFCXiZXRRBgORh8LNxZB+PjWutUlvb0Yhwbd5JE+B1iGUNl3jAZ4UQuV5imMw7V0/9rCdxXSw6aAiJu8PotM28ShP51Q7EEFaDzznamTp8U+kU7wKCa/0Bz9WoZ8xwKtJIIqxHU/RC+TjlD6uS0gqIASGUfSE2xQGz68kV+L6Ayitxa1XQ0HY5+biSrd1MvUPRo/8M9/lY/sE4hKhosht5pPF59+MAe4GddAXMyxxnoE/tK/YnHKj3HdEuvf7jwpjI/fI+o2KnUObvXuH3+EosFhDWIgXIFjM2+P4Z5kQRmJRvPSb4UtajlKUoTQIIs+UHSKxDec/NkT80NyJ2NOTwcOJNEzYjgauDlYSqsk3wAQq+rDdrmLboXilSkUaAseW81XSHgspzh0Bjp/9vjufUm+ER1rZpfenUWY7r00OD/BcfQTga+Mz8S3an7eXnqdTlXevnUinCfhyy04+FeH4qDtw3tC6XXRVPAtyGLrT/JcIWDMtGe5YvUWMAHk5CSaCT3a/oGGm8YvOhMUg3/Oxs+yHN7DYGWy7EBCBeRrynYL8wsxWkz/019JmTbLWc6HFOMWyCCooXiDSlcAB9Bs25QpisbzBKL58dndExUH054InBsHLzalmGw9iQd18w0lot/rWtiZKGnQBVXX/Y/obNU597FqAcEro5qTLapeVR0i0dRt/iowYWCKZjokHIOJCyQplAIYkjlVwJ41OEYMW1ITELrVC1//u3ZgVxxqz741lb0uQYYFTH5y73WeM7uaD+XOwi8TR/QX290oxFUlQGbDnN7t8FJv5uR9zwl1piDtbWV1YPGL3II4wNkv/VnjK7cPdKA84Z69/2SmY620SNMyCnSnbD5dDFPaaLlRzVC1HTQXiBzePEsTte2w0BV78GupBu7mtufGeG6XgHb7G0MprXKuOzr4c8CMYLFQJEHF"
    }
  }
}
