{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "tinyrack-s3-secret",
    "namespace": "kube-system"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "tinyrack-s3-secret",
        "namespace": "kube-system",
        "annotations": {
          "reflector.v1.k8s.emberstack.com/reflection-allowed": "true",
          "reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces": "longhorn-system,discourse-system,issuary-system,memos-system",
          "reflector.v1.k8s.emberstack.com/reflection-auto-enabled": "true"
        }
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "AWS_ACCESS_KEY_ID": "AgAABcDkKdRdHNDMAt7iSgGiM7C9CabLBvxwf8HBzg27MouElP4+LRdnOKBPSZPpO1c2nMG+0O3AGAkxkblgUK7N2ft0PIGuBaan7KH8JySFKmazfB7jNdsZQg6inM7Tz7QeUYzzMqBieC8VhPzrBs3yOK7aL3qrfMXrLDcpJYdN6AzSi0QRNoi0yL6bx7AGHg42TeS+1kmFJYktdeLdAvUJxVRBTyFWrj8rCXXLa4eRPjthZHMbzz4/enimBN3VsRE3Y5X1LFzqEAuZC90I8YSdhkW4I2XzyCp5fsBwJ3jU6U839MZCFGxHAs2BG++o6eiqeDLZAHeJryUgaiXwmKG6m+SC7Q6Wb5RipvjCgvXxyi1aIiuowtS5NMZjP1M0hDueHb/U9k6BEvMf50kym/PminTPMsg8pQHKQZo+8mKLiHq56gu6feaUG7ZwSxlDF37LcDyZVwNpZjn1Dm9zSf8QNg691amIjmuRfGW3PHkxyCXkree2Pyi3i8quvgFff6nvuufssl/etIehy0WRQ/Rd5iANUBpdKIu1KElDNjQHegrovh8QzrDQUanOyOw+Hkw3AWP1JDwdsoOXb/kJENS1NAaaNrhU6y536VXS9HKdRUqD8HvITBOnTADyE4uk/SyFMPRqnVDE1XSPSAclcfkk3dySut1DCAXyygFJ0zg9CsHBH1ervR97K080EWY2wUiAEKJLOnGvjkvkaGDiSGtMRIKJgg==",
      "AWS_ENDPOINTS": "AgCZmxP2cHXTxzpBX61IcaTJTyAqil3FHl4fXczeH96V4ahbQCD7Wv0y1c2lPE3cOY46RCHAfWel6l+MNslDC3vC5fOL8OC0OeqIZJBGCP+TdrHZHWBcQD+B7zJAdsm6x3aljQfbDQ5LDC57Ycsxp/ai0viTvu4o/9TvjrLUP7Uxdz+DvdfQkqV/OrznpGp3fsNGjBbNcsdrl7FfQqIZ3bAJLYC2XXYMysj8ym0g3MygtYv56BIShna/BKRRSek5Tkip27JHHmuNLoUjKw9+pJyQteX+f2it5uXoI11f6C/gDLlBCs4o84xm00/WExs/1gq/qyYG27E7oi0EEfv9qdDmhNX87InfH7CM7rw+fOb+8lSIbB4H2lMzyLRHkqdArJALLvHvxvoDJ6i+SOUwKN3OYXiPP+ktPwUykfWt2Gh5bYW70WYAJ/NV05b4RzN6LZe5llqM7VFAvyf2V51648HVYlsDP5tieJaBcOuIBiG4SaLt16z3UOeM+4/9fhMqgSsCOBtqrq0P1ve3k4kNCyAS5jvSIrfAZriiDcXDy0OuDBaxQ5jFmfWHyleWTM0HHbSjhwKIJh8ojAiLgmfbfiecY5eOj8IF5YhRwepKlrmaJY4i3VDuRk8REJsOg0v5dJ+eI8qNwfF/c7wGnj3mk8+FkopF/LXuBBO09t/7mMjiONXuE5nfiR0situM0M763sy5gHvwkhBCm+/Hp0dmIQiyhKsd6y58mIzPuSWr81fj48bA2g==",
      "AWS_SECRET_ACCESS_KEY": "AgBFYMjT9Za9UYagZT3+62V+kKyAA2WsOPPokJjfWc/qBCmwkbxVMLPE/r0yWJfO2xPixVum2dni2hMKLS8AqCI2L+F1g7TUjGL6GOJKBnKhft09Iru+JySVjTznRdmt/X7xQieth2y87xHrV+2jXKDCZfXIYXmtcYPnpDeEHi8DMVZJlqwIMBC5oXC6lwewOItwQ59CIziVB3n3KiYcwsqYdNJZsuoZW0hP6AxkA7HLNqP4oyh6jEUfT3mUG2yMzF5qvOY7+Ri/y6HR2DpikJtTdR8UzdzsgyPUq8moXacIxP2+ZpVPHN2uk0Gl9adgQ+hQkXhrK0p4yBPifLg7t7l3a/l1JpUgn6x/PAkO0AFSiLh4CrMkHKJeE4M7pGbZx4zpq+vra5vMDOZQ2gOfUZndRCWxGEscaNavzI4HJbzDPRpvgMDrdebGBGHOdAwxE/tygTUMGCLNScsT8dyOoV/hq0Etq2pkCMrzseg4orWSOzsEyY9D1j7OPDlXAcLROolPT2cloELZVsOIvjfeP3C0aK9JToOk8luM8WR9SAPykTGgVgIJ/1Ktr4Tt+Nqv/aDKCmYJfYwC7TVsw0D19ZYw0CKVB7BjI/yW4+Ee6DW1xOoc2cvxf2Elsafi5/eugUFg+wPa+mj6J3TCXMzg78Zw5W9JH1z43kLc5veLwN9nTu/B0ZZYq2gZZY3GFyqG8R1JF0zFiC++kJxVkggp3qJzp9K8/AbT2Qcx6qBm8KjeyjbRgEDTjh7B"
    }
  }
}
