{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "tinyrack-s3-secret",
    "namespace": "kube-system"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "tinyrack-s3-secret",
        "namespace": "kube-system",
        "annotations": {
          "reflector.v1.k8s.emberstack.com/reflection-allowed": "true",
          "reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces": "",
          "reflector.v1.k8s.emberstack.com/reflection-auto-enabled": "true"
        }
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "AWS_ACCESS_KEY_ID": "AgAEOZZafFyzXZM+3TGFNnZXBkHcm0Ob7XzvScuOsZzVpzdJDZg19FE2HyQqy7xsKgZHBMfhLK6VRDoxHUhZ7tdZYWDfa4lR1AR+nqmLgl4ko8A/pxY8T9zIehHPMtpFK01vvRV8oAKOVICDXGjwhg01PGJC8gjLBtF/ajY/JKmDVmnZMIHc/cyO9vvnqmAdibJfXzC6cf6JfIstw7gAZI3yiMs+qO23u06UTbIG8WUZtyIDwIaiCxnMthvQ1oxZsPjcMB7tvWhXDk++TDbZ6x9/3iYxlK6HOjMXnMioqxbkKmACh1CwnlxMpK7YqgkhpPqCA+9uR8nYWuXRO7dV7JDnMzDSCguJEsbPst9jmlv/PUjzuQHyoZaC1/f4H8/vLzcSTHW512YYd7sZe+tLj9U8jtxZ2kHsK/AY8chKfsResBzMq/xjoIPOrLiuMiENauQ4Szlct1uW2k0oz8b1SWtlfSSqextfoEOxKL30J9bpcwhcYlycg2JzLRdcWZlUps5OJKjruRIeeMfmPTckIjT8H2Qn9Jmw+YX98LoeN87X6qpCwtS90ecOC7F9isX2c2a4TrLjV4i+mMiFH/hVNJcb/Lw3c6D+P6wabFRkXLKoQ7Oos/nZgW8Ah7MFXADma397VfKG+7Y9823IbDw/Lr0P6y+i6PX+tUX5vRTJVfazuE3w9b96L5KHxma7M2NypxKO1vu6Usq0Q0RgIoM7WNWS4o1wuA==",
      "AWS_ENDPOINTS": "AgC8mnUwgToxyj2LEl1NV/z3vbVQGE9runLidXslGqe5e5A5KQjHeHMoUY4PqAyJQF8Z2MNHGSgQqPYPZpscWAlDe3n6RN2kVjgDW2UWEBT/28J4huxGg7Xk/4keVZdBPPx/ru56ORyEsdxR+BMIseFnIFd4hwghTAIIaPD1KLncDipiooK3m2e/bRNykMpBF7zFb+xOMRsxiunRrcdSI+rxC27oMyWmMlhCXrfIhUeSqPda1migfwPh2jiPkT4FbLQrG62fuOHRkeguaDTQW0MpGu/5488LnRWEAtDcj/sjKhqwIMYjWzZwOLp8AX/MIOXq/fub0Kc1CvSnb475xfgy9tgeg1HckDYp2gzOl718aVSxNdYoWekDzPqyhwtvczjS1tYT+CNGTdKg4E+stTETALK2c+5y+R8MFjqZtZa4J6wm9b/x5Mbtxe3KuP1l+S93D2Dd0cDdd8OwzzLjEH8M9FMVHC7ML7ziJ8Ubqq9W2lP8pObRfSSX93Jj35lidoyGMxO7XYyhsb4xuJGPN+DKXY1yEK6gwhJ/Do2LXdc9fQRSSn7lYZQQ8EiexkdOqXAbGTlW9GNpJtuKKISbAfedkSrGGMYjmvqvORZmqxO0FoUvIc7OPwjF5du5PabUxC7txjTltoeBeXAGBTispdpfM/J9XiKaPOBlQrI2Hgb5IBK275rAfI0HQE4/XinYGShqgtROHfzLq4YRt2NsZKn0iwpilgvIQZtSfSfOQHLRVol/GA==",
      "AWS_SECRET_ACCESS_KEY": "AgAFIFdB+keqrQwRJvgEuxB9typezma6VGS92oA4hpgJ4DTLtCpPCss3cn3GGkXKFs0aMNa/6xLt7qJd+ws4bLUny1jUw7UJkQ5UnT6sTgl/ukDdfR7Uc6wsbtUcWq2YxJfTWd9+Y5h/IUeOmJPWZC/I98HBzkCt7zcakMAfcSAOE8QKTkoXkoFioJSiUwlsCi6hZHY40Z4xPHqYIbCy0MseoBZup0sFwLOmZgV/hBb24hIU39Y/3T4UNdnCaYJYUyLmzDZ0e5dc43OunPJhEoBL1HsUeWG6rWiJCJYc30yaujDz5IST7mr9tO6UfEDva7G/gy3IJ66q8uxjJX/8ZhNkchp04wRDcErZpxsUcAf0iRlp7B7eKAUHijWzXOJ7PjtL3WY4MGGNvuQFh8bx0TRhbe/cCSFuYdfWnpP0PKvLrDNgNIOpimQEAH3AuYTS5Usd7dO+MUsl78uy/2pYbZBmgjGjWBdAoCTNMGOZ1dNn2G5Bxc/RVc6vFVF0kKbf/dh5iM1LF3lkaYBKXHp1nSC4Y71WrVQAZjbFYDrsoBuRvsuQQjvYQ04yYdoS3W/cvato7wBOVzVlH7wK0xfFfhfIyuA8sDepfioynCJgH5uljk+ZhTIUnBRGK+tC8V8VagfI5OIvpWtJ513bJC6PD1hRjo6lklnm6uim+pYw6YWf0ia0f4vdkFzvPlb5Apoq9VFtAvJpHETYe4sfGRDqDDASG+n/3okrUIIq4v4R1Bw9GJNBGU6vTFmf"
    }
  }
}
