apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: discourse-database-15-backup-store
  namespace: discourse-system
spec:
  retentionPolicy: 30d
  configuration:
    destinationPath: s3://tinyrack-prod/apps/discourse/database-15
    endpointURL: https://fsn1.your-objectstorage.com
    s3Credentials:
      accessKeyId:
        name: tinyrack-s3-secret
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: tinyrack-s3-secret
        key: AWS_SECRET_ACCESS_KEY
    data:
      compression: gzip
    wal:
      compression: gzip
      maxParallel: 8
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: discourse-database-15-cluster
  namespace: discourse-system
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: "enabled"
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:15-bookworm
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 3Gi
      storageClassName: local-path
      volumeMode: Filesystem
  monitoring:
    enablePodMonitor: true
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: discourse-database-15-backup-store
  externalClusters:
    - name: discourse-database-15
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: discourse-database-15-backup-store
          serverName: discourse-database-15

  enableSuperuserAccess: true
  superuserSecret:
    name: discourse-database-superuser-secret

  # 신규 클러스터 프로비저닝 시 주석 처리
  bootstrap:
    recovery:
      source: discourse-database-15

  # bootstrap:
  #   initdb:
  #     database: discourse
  #     owner: discourse
  #     secret:
  #       name: discourse-database-user-secret
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: discourse-15-backup
  namespace: discourse-system
spec:
  schedule: "0 0 */4 * * *"
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  cluster:
    name: discourse-database-15-cluster
