apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: discourse-database-cluster
  namespace: discourse-system
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: "enabled"
spec:
  instances: 1
  postgresVersion: 17
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 3Gi
      storageClassName: local-path
      volumeMode: Filesystem
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: 30d
    barmanObjectStore: &barmanObjectStore
      destinationPath: s3://tinyrack/apps/discourse/database
      endpointURL: https://storage.winetree94.click
      s3Credentials:
        accessKeyId:
          name: tinyrack-s3-secret
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: tinyrack-s3-secret
          key: AWS_SECRET_ACCESS_KEY
      serverName: discourse-database
      data:
        compression: bzip2
      wal:
        compression: bzip2
        maxParallel: 8
  externalClusters:
    - name: discourse-database
      barmanObjectStore: *barmanObjectStore

  enableSuperuserAccess: true
  superuserSecret:
    name: discourse-database-superuser-secret

  # 신규 클러스터 프로비저닝 시 주석 처리
  bootstrap:
    recovery:
      source: discourse-database

  # bootstrap:
  #   initdb:
  #     database: discourse
  #     owner: discourse
  #     secret:
  #       name: discourse-database-user-secret
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: discourse-backup
  namespace: discourse-system
spec:
  schedule: "0 */30 * * * *"
  backupOwnerReference: self
  cluster:
    name: discourse-database-cluster