apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: discourse-release
  namespace: discourse-system
spec:
  chartRef:
    kind: OCIRepository
    name: discourse-repository
    namespace: flux-system
  interval: 5m
  timeout: 5m
  releaseName: discourse
  values:
    global:
      defaultStorageClass: longhorn-rwx
    sitename: "타이니랙 포럼"
    auth:
      email: admin@tinyrack.net
      username: tinyrack
      existingSecret: discourse-initial-admin-secret
    discourse:
      # plugins:
      #   - https://github.com/discourse/discourse-doc-categories.git
      #   - https://github.com/discourse/discourse-data-explorer.git
      #   - https://github.com/discourse/discourse-reactions
      #   - https://github.com/discourse/discourse-solved
      #   - https://github.com/discourse/discourse-apple-auth
      #   - https://github.com/discourse/discourse-ai
      #   - https://github.com/discourse/discourse-rss-polling.git
      #   - https://github.com/discourse/discourse-bbcode
      #   - https://github.com/discourse/discourse-translator
      #   - https://github.com/discourse/discourse-topic-voting
      #   - https://github.com/discourse/discourse-post-voting
      #   - https://github.com/discourse/discourse-adplugin
      #   - https://github.com/discourse/discourse-prometheus
      #   - https://github.com/naidihr/discourse-category-headers
      resources:
        requests:
          cpu: "250m"
          memory: "512Mi"
        limits:
          cpu: "3"
          memory: "8Gi"
    sidekiq:
      resources:
        requests:
          cpu: "250m"
          memory: "512Mi"
        limits:
          cpu: "3"
          memory: "8Gi"
    persistence:
      enabled: true
      storageClass: longhorn-rwx
      accessModes:
        - ReadWriteMany
      size: 5Gi
    postgresql:
      enabled: false
    externalDatabase:
      host: discourse-database-postgresql.discourse-system.svc.cluster.local
      port: 5432
      user: discourse
      database: discourse
      existingSecret: discourse-database-secret
      existingSecretPasswordKey: "password"
      existingSecretPostgresPasswordKey: "postgres-password"
    redis:
      enabled: false
    externalRedis:
      host: discourse-redis-master.discourse-system.svc.cluster.local
      port: 6379
      existingSecret: discourse-redis-secret
      existingSecretPasswordKey: redis-password
