apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: discourse-storage
  namespace: discourse-system
  labels:
    recurring-job-group.longhorn.io/backup: "enabled"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: longhorn-rwx