apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: discourse-storage
  namespace: discourse-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-rwx