apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openwebui-redis-helm-release
  namespace: openwebui-system
spec:
  chartRef:
    kind: OCIRepository
    name: redis-repository
    namespace: flux-system
  interval: 5m
  timeout: 5m
  releaseName: openwebui-redis
  values:
    global:
      storageClass: "longhorn"
    auth:
      enabled: true
      existingSecret: "openwebui-redis-secret"
      existingSecretPasswordKey: redis-password
    master:
      persistence:
        size: 16Gi
    replica:
      replicaCount: 0