apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openwebui-storage
  namespace: openwebui-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-rwx
  # volumeName: discourse-storage-pv
