apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openwebui-helm-release
  namespace: openwebui-system
spec:
  releaseName: openwebui
  interval: 5m
  chart:
    spec:
      chart: open-webui
      version: "8.14.0"
      sourceRef:
        kind: HelmRepository
        name: openwebui-repository
        namespace: flux-system
  values:
    tika:
      enabled: true
    ollama:
      enabled: false
    pipelines:
      enabled: false
    replicaCount: 2
    persistence:
      enabled: true
      storageClass: "longhorn-rwx"
      accessModes:
        - ReadWriteMany
      size: 10Gi
    extraEnvVars:
      - name: DATABASE_URL
        valueFrom:
          secretKeyRef:
            name: openwebui-database-uri
            key: uri
      - name: ENABLE_WEBSOCKET_SUPPORT
        value: "true"
      - name: WEBSOCKET_MANAGER
        value: "redis"
      - name: REDIS_URL
        valueFrom:
          secretKeyRef:
            name: openwebui-redis-uri-secret
            key: uri
      - name: WEBSOCKET_REDIS_URL
        valueFrom:
          secretKeyRef:
            name: openwebui-redis-uri-secret
            key: uri
      - name: BYPASS_MODEL_ACCESS_CONTROL
        value: "false"
      - name: ENABLE_FORWARD_USER_INFO_HEADERS
        value: "True"
      - name: WEBUI_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: openwebui-secret
            key: secret-key
