apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openwebui-helm-release
  namespace: openwebui-system
spec:
  releaseName: openwebui
  interval: 5m
  chart:
    spec:
      chart: open-webui
      version: "7.7.0"
      sourceRef:
        kind: HelmRepository
        name: openwebui-repository
        namespace: flux-system
  values:
    persistence:
      enabled: true
      storageClass: "longhorn-rwx"
      accessModes:
        - ReadWriteMany
      size: 10Gi
    extraEnvVars:
      - name: DATABASE_URL
        valueFrom:
          secretKeyRef:
            name: openwebui-database-uri
            key: uri
      - name: REDIS_URL
        valueFrom:
          secretKeyRef:
            name: openwebui-redis-uri-secret
            key: uri
      - name: BYPASS_MODEL_ACCESS_CONTROL
        value: "true"
