apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openwebui-helm-release
  namespace: openwebui-system
spec:
  releaseName: openwebui
  interval: 5m
  chart:
    spec:
      chart: open-webui
      version: "7.7.0"
      sourceRef:
        kind: HelmRepository
        name: openwebui-repository
        namespace: flux-system
  values:
    extraEnvVars:
      - name: DATABASE_URL
        valueFrom:
          secretKeyRef:
            name: openwebui-database-connection-string
            key: connection-string
