{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "cloudflare-api-token-secret",
    "namespace": "cert-manager-system",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "cloudflare-api-token-secret",
        "namespace": "cert-manager-system",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "api_token": "AgA831+zRswtnh2Wa6YGdl/KkxwXWs/ElCe72O0Gew9vieN4z6hUYS9TrxoCv+j1DYlRgclP70Acxgfyy3UNJu1MA5Lq3Bn0FZ664apSHFHjQz4aP1rWIJMClh94tkcnFyNYCtleYz1ntJmpHnezGw7JPzrd/HxCkAZHhpCluMvMbTuP4azIeHMM+yeAYLcwt/H/BHX07fsoGTevnhs3DHM7To1QmGHEkXEWasLpcxbQfP0OSh+IiDhMhvEwgncvmsIFxWHmlS7PTOTBM8TmUzFYkyWvbl44tMZ+X2hlJTetMQWCnoBbAH2nlYAt2CgoAvk7ql9T9eud+rumJ1b2vmOO5NbmyEpTdK130JUibkKOKCa+EZRo3YrzOL19RqCQDuTwNX6MLPcEvsjHgBFALWtHv+vhUB8oVjYDyMZMusiGy9ZZxiYD8P289inKO+QSKhfTA2wCitMp1ZOHzliE8t7+u2W+16xKKZCf5KFjPwaFhHmxEotA2Mrdz8ZPBJTfGVsgWeyHQ8EIL9JSP3HjQezICMOYbEdkCLCIAIwtmpCuTQnsFmHteE4hOpupFk/e8fcW6asovzXzIw4tMgQePf7FDWExDrj7+3RDON9sS4+hV5mi5SZFA8cmHRte/McoASaorHuy4mvRVJWnn9j2tIfW98gTsVQUX61PGdqKU6U+imC34H4XgMpTFE2s2ElKjeFEku0KUb4aRO+u0QSj4XhThEn2Jo0fcAY9dUTxsrYIdFBz1l8Br/+o"
    }
  }
}
