apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflare.api-token.secret.yaml
  - cert-manager.cluster-issuer.yaml
  - letsencrypt-certification.namespace.yaml
  - letsencrypt-certification.certificate.yaml