---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: telemetry-credentials
  namespace: monitoring-system
spec:
  encryptedData:
    TELEMETRY_TOKEN: AgC1lst161OW4WvttxEUsDjQ7AdqOyHx4gJ2rwNgKpzVeg6dKfruX0thvlY5PJ2Z5XZEl2ztwL+oxWcC5/459gTdCn7WAg1cI+hjEhksZI0l4hHQfKEEZZdY6YTMuHYWafDufFdUmAvzkVni4lDIa4iisHxEIYaKSHtAna5MHjglcIJaifyJh6P3PUPByeRAyzJ8lcnYhJVEQAGw4FzjOi/vnJXwzR/3m4ZBsoQGhs9i7LRXqEoY2FSAFuRdoBT9r4O/Z1eWnwgmrrmysSKEDWTdxD6+6aZ65O1/Lt1giMQe3oonAkfwpJM8ZMtAjamajOgfT02Q4HYjmecvWVKUgScQQwFwj3HPTbcO0JQNs3gZ5CqluRa+lYud16bYqifcxSUK7zlsrQtE9JwmZjSQTI99Ibtvd4l2poEKdDireqfJc1yEL/pfvLFo9h8g8QjA6c2kFVSu0ePYNayXIBmdvYmqOtOgc/ZAVUyYrspdbmMqfEVMx8J40y/embl2RZwS12uB9TciS9E5jPJyOl5g4SDevSIrYPPYWfoIBLY+zBnZ92QJVhMR2xH8jlVxht4dxOQQ8YcGcmC7yDFhvcMny1Zwvg4JiTPWC5/HcJLW9iQvJDQP70ofgW/KN7wXXI1LXYAan+cTi3BPBK1hlhA8Z4z2X9tnajAy3co2NI+igLKH9GcU+oNqLTcjqbUtVf5VZsBKb4pnR244CWzYa+JGmSh5eV69RkgN/FAnJuxhe1Ch/qDu2HAQniBnm1ue7CAgAbR04CdHwIZ799bRjRdaAcua
  template:
    metadata:
      name: telemetry-credentials
      namespace: monitoring-system
