---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: telemetry-credentials
  namespace: monitoring-system
spec:
  encryptedData:
    TELEMETRY_PASSWORD: AgAPI6isTHr1PX7XPCFXA1QCK5FVW5GvPHArLsT4SeO34d4KD3GfEcs76kOrR31UNeZqraCtl4je3ChlbkgPwlvoKRyDhI2m2E/vjAtF5Vg3x9I5BZmCsxupNSg6IL+SjX7GB2N89BEKaPL9RofFzVa053A619AESuj+kveYq7NK+F7tYNj7bMBGFTlVgmJ2fmbTNjSxO0Nmv0OPemwfXOigHnywGJ253RD4umnzN2qUDICxbhvxN/Bvrxvee+62TzVXmivPyiabuGAgU7GbUKFuin+PpW6eZs/G7uZYL58bnACBYDwEWKOvde+FUJ5M3uyZymwFIs9WnY91ym7FvIQ1tE5OcX6IIkbkmWKjrCopSkztQKUYD9q5/gcKgZ4KeTDvO0vXvNZliSO61zfzPiphZ4xoT6r9sIgvrdm5TdY+ADYGTm/n193dCQ14LCYnW1zAjo9slZ+ImOhBYBSaQWyjK7M9sNHE5vY+5mwP4sPduB5OURcxbwE24AfnTnbnzAMVaS9IHxRb4rGXjfw2YfvYuWzQkEaqITuc2IbPogZjZjP3ShZ3PKnIrr9jxWrpgI34bVzDi0d9Z9haTRMdBYwo3AXS2115+rFyTg/+Xbv42vcyOWqmXeH0dctTTaOh5UhKYiPn2HDirlLzRepQCq77B1/8BNx8UeU5Xlji1nJyyTWgHOfGGOrJmM7yyO3DrfXbIuMBRKPfVH/t9TbxOxKzRjXAcCRmPRPEAGpkDSxWZ/VfVvbtscxhS5gooHa409s=
    TELEMETRY_USERNAME: AgCyXuX7eI9SIK7nITU8zj9ZAELZszwbl6qJ588Sd+QTEhjw3h3uti9H9QDZO0vIu08RD63nxCZe56H2OK/y9Y+KOSf2H0CjZTvpwhC8KTvC7AbIz6nReRGcS5tsMIiDt2OhKvBJt2ZCYTrVZenPIulx8QHeHSix2Bep43BDsOSkkU+NnTjdWJ0zeXwBPmRTFmhw9zAYwYcuItV7yrCtrf9On8DfLy2NftehXqZiuoWo+Bj3bIp2u89tTgxV2fdv1K2FGBQKIK8u6viOXntBCdpNK+q36EiKtztAlYcV0kNRSZpr35KPJ9ZsiIbGHi9TVWM2nkJuLOrYlr6rgXOxIbPgfNbwlAwEpxs56hPP/WZ4cQABWX32Pwd0NQ1bHlQEhiNv8orZAaJoSKu9x4W6Qauckrm7ec0hirn/Rd38dKf8wA1qw2ZzbIW5vystaz/m/58NkZCT5rUgkV56lt5G+0RiRohN320OR4oPx0dDwCCcNnwZr3Dq5Nmy3sznvP9IR93FD4TGoP5MU1SY5+WTXuKBmxwIhWiGA3ZWWxPYgE2x09UoVi3GowWzAFP92gABCeHjR9sq7nWp7C7eMvqwoRAaZDZc+x0VZseI83QIx8GM/WAIea7BPoYr0cfnmWL9pdeW5D4wnIOKssFvgf1M8ByElXFaeJBNNG038Ewk/z1U3GDocJqz2h+04N1+zVDCBV5L7WfbLoJLbA==
  template:
    metadata:
      name: telemetry-credentials
      namespace: monitoring-system
